name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test using GithubActionDemo scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build
        env:
          scheme: GithubActionDemo
          platform: iOS Simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          file_to_build="GithubActionDemo.xcworkspace"
          xcodebuild build-for-testing \
            -workspace "$file_to_build" \
            -scheme "$scheme" \
            -destination "platform=$platform,name=$device"

      - name: Test
        env:
          scheme: GithubActionDemo
          platform: iOS Simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          file_to_build="GithubActionDemo.xcworkspace"
          xcodebuild test-without-building \
            -workspace "$file_to_build" \
            -scheme "$scheme" \
            -destination "platform=$platform,name=$device"
